### ISSUE TITLE
Sort out the documentation

### ISSUE THREAD

**Issue by Lukasa** [requests/requests-oauthlib#48]
We've finally got some stuff up on ReadTheDocs, but it's not great. This issue is an umbrella tracking issue, so I can tick stuff off as we go. Here are some things we need to do: feel free to suggest more in the comments.
- [ ] Sort out the README (partly in  #46).
- [x] Sort out Intersphinx (see #47).
- [ ] Remove lengthy worked examples from the API docs.
- [ ] Put lengthy worked examples somewhere else (see #46).
- [ ] Improve clarity of API docs.
- [ ] Improve landing page.
- [ ] Tutorials. Lots of tutorials. A whole tutorials section (see #49).

**Comment by JonathanHuot** [comment]
The documentation has been improved a couple of times across this ticket and probably the description does not reflect the current state. I'm suggesting to close it. Feel free to create another one with latest remarks about doc if necessary.
